-- WBS 3.2 Finance Core Schema Integration
-- Created: 2026-04-22 (Auto-Generated by Antigravity CTO)

-- 1. 청구서 마스터 테이블
CREATE TABLE IF NOT EXISTS public.zen_invoices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_no TEXT UNIQUE NOT NULL, -- INV-YYYYMMDD-SERIAL
    shipper_id UUID NOT NULL REFERENCES public.zen_organizations(id),
    total_amount DECIMAL(19, 4) NOT NULL DEFAULT 0,
    paid_amount DECIMAL(19, 4) NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'USD',
    due_date DATE NOT NULL,
    status TEXT NOT NULL DEFAULT 'UNPAID' CHECK (status IN ('UNPAID', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELED')),
    metadata JSONB DEFAULT '{}'::jsonb, -- 비고, 은행 정보 등
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    created_by UUID REFERENCES auth.users(id)
);

-- 2. 오더별 비용 상세 테이블 (Chargeable Weight 기반 산출 데이터 저장)
CREATE TABLE IF NOT EXISTS public.zen_order_costs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL REFERENCES public.zen_orders(id) ON DELETE CASCADE,
    invoice_id UUID REFERENCES public.zen_invoices(id),
    cost_type TEXT NOT NULL, -- FREIGHT, FUEL, SECURITY, TRUCKING, CUSTOMS, etc.
    unit_price DECIMAL(19, 4) NOT NULL DEFAULT 0,
    quantity DECIMAL(19, 4) NOT NULL DEFAULT 1, -- Usually Weight or CBM
    total_amount DECIMAL(19, 4) GENERATED ALWAYS AS (unit_price * quantity) STORED,
    currency TEXT NOT NULL DEFAULT 'USD',
    is_revenue BOOLEAN DEFAULT true, -- true: 매출(AR), false: 매입(AP)
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. 오더 테이블에 정산 상태 컬럼 추가
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'zen_orders' AND COLUMN_NAME = 'billing_status') THEN
        ALTER TABLE public.zen_orders ADD COLUMN billing_status TEXT DEFAULT 'PENDING' CHECK (billing_status IN ('PENDING', 'INVOICED', 'PAID'));
    END IF;
END $$;

-- 4. 자동 비용 계산 RPC 함수 (Chargeable Weight 기반)
CREATE OR REPLACE FUNCTION public.calculate_order_costs(p_order_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_order RECORD;
    v_rate RECORD;
    v_chargeable_weight NUMERIC;
    v_total_freight NUMERIC;
BEGIN
    -- 1. 오더 정보 및 화물 스펙 조회
    SELECT * INTO v_order FROM public.zen_orders WHERE id = p_order_id;
    
    -- Chargeable Weight 계산 로직 (Air: 1:6000 기준)
    -- 실제 운영 데이터에서는 cargo_details JSONB에서 파싱
    v_chargeable_weight := COALESCE((v_order.estimated_cost)::NUMERIC, 1.0); -- 임시 매핑

    -- 2. 요율 매칭 (Air/Sea/Express 구분 및 최우선 순위 검색)
    SELECT * INTO v_rate 
    FROM public.rate_cards 
    WHERE origin_port = v_order.origin_port_id 
      AND destination_port = v_order.dest_port_id
      AND service_type = v_order.transport_mode -- 'AIR', 'SEA' 등
      AND status = 'ACTIVE'
    ORDER BY priority DESC, created_at DESC
    LIMIT 1;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'message', '유효한 요율 카드를 찾을 수 없습니다.');
    END IF;

    v_total_freight := v_rate.base_rate * v_chargeable_weight;

    -- 3. 정산 상세(zen_order_costs) 자동 삽입 (기존 데이터 삭제 후 갱신)
    DELETE FROM public.zen_order_costs WHERE order_id = p_order_id AND cost_type = 'FREIGHT';
    
    INSERT INTO public.zen_order_costs (order_id, cost_type, unit_price, quantity, currency)
    VALUES (p_order_id, 'FREIGHT', v_rate.base_rate, v_chargeable_weight, 'USD');

    RETURN jsonb_build_object(
        'success', true, 
        'chargeable_weight', v_chargeable_weight,
        'rate_applied', v_rate.base_rate,
        'total_freight', v_total_freight,
        'currency', 'USD'
    );
END;
$$;

-- 5. 보안 설정 (RLS)
ALTER TABLE public.zen_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zen_order_costs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Shippers can view their own zen_invoices" ON public.zen_invoices
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.profiles 
            WHERE profiles.id = auth.uid() 
            AND (profiles.org_id = zen_invoices.shipper_id OR profiles.role = 'ADMIN')
        )
    );

CREATE POLICY "Shippers can view their order costs" ON public.zen_order_costs
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.zen_orders 
            JOIN public.profiles ON profiles.org_id = zen_orders.shipper_id
            WHERE zen_orders.id = zen_order_costs.order_id 
            AND (profiles.id = auth.uid() OR profiles.role = 'ADMIN')
        )
    );
